gtest_case('tests',
  sources = [
    'affine_test.cc',
    'complex_test.cc',
    'linear_test.cc',
    'matrix_test.cc',
    'vector_test.cc',
    'quaternion_test.cc',
  ],
  deps = [
    '//etl/math',
    '//test:assert_throw',
  ],
)
